# MkDocs Configuration for Inceptor Project
site_name: Inceptor - Multi-Level Solution Architecture Generator
site_description: "AI-powered solution architecture generator using Ollama Mistral:7b with Inception-inspired multi-level approach"
site_author: "Inceptor Development Team"
site_url: "https://wronai.github.io/inceptor"

# Repository
repo_name: "wronai/inceptor"
repo_url: "https://github.com/wronai/inceptor"
edit_uri: "edit/main/docs/"

# Copyright
copyright: "Copyright &copy; 2025 Inceptor Project Contributors"

# Configuration
theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode  
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: "Roboto"
    code: "Roboto Mono"
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  custom_dir: docs/overrides

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: "On this page"
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: yourusername
      repo: inceptor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            group_by_category: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
      strict: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - privacy:
      enabled: true
  - social:
      enabled: false  # Set to true if you want social cards
  - tags:
      tags_file: tags.md

# Customization
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/inceptor
      name: GitHub Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/inceptor/
      name: PyPI Package
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/yourusername/inceptor
      name: Docker Hub
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Replace with your Google Analytics ID
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Page tree
nav:
  - Home: 
    - index.md
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Features: features.md
  
  - User Guide:
    - guide/index.md
    - Getting Started: guide/getting-started.md
    - Basic Usage: guide/basic-usage.md
    - Advanced Features: guide/advanced-features.md
    - Configuration: guide/configuration.md
    - CLI Reference: guide/cli-reference.md
    - Examples: guide/examples.md
  
  - Architecture:
    - architecture/index.md
    - Overview: architecture/overview.md
    - Multi-Level Design: architecture/multi-level.md
    - Prompt Engineering: architecture/prompts.md
    - Context Extraction: architecture/context.md
    - Ollama Integration: architecture/ollama.md
  
  - API Reference:
    - api/index.md
    - Core Classes: api/core.md
    - CLI Module: api/cli.md
    - Utilities: api/utils.md
    - Exceptions: api/exceptions.md
  
  - Development:
    - development/index.md
    - Contributing: development/contributing.md
    - Development Setup: development/setup.md
    - Testing: development/testing.md
    - Code Style: development/code-style.md
    - Release Process: development/release.md
  
  - Examples & Tutorials:
    - examples/index.md
    - Basic Examples: examples/basic.md
    - Real-world Use Cases: examples/use-cases.md
    - Integration Examples: examples/integration.md
    - Custom Prompts: examples/custom-prompts.md
    - Troubleshooting: examples/troubleshooting.md
  
  - About:
    - about/index.md
    - Changelog: about/changelog.md
    - License: about/license.md
    - FAQ: about/faq.md
    - Roadmap: about/roadmap.md
    - Support: about/support.md

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/termynal.css

extra_javascript:
  - assets/javascripts/custom.js
  - assets/javascripts/termynal.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Watch additional files
watch:
  - docs/
  - inceptor.py
  - cli.py
  - README.md

# Development server
dev_addr: "127.0.0.1:8000"

# Build directory
site_dir: "site"

# Validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn